spring.application.name=personal-website
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Personal-Website
spring.datasource.username=postgres
spring.datasource.password=log3in7dat

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=dcgpqdljt
cloudinary.api-key=214477338148235
cloudinary.api-secret=iF53a4gheVbks4KksEBO_IvbLVE

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
